on:
  workflow_call:
jobs:
  streamDeckPlugin:
    name: Package
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: source
      - name: Make build directory
        run: cmake -E make_directory build
      - name: Configure
        working-directory: build
        shell: pwsh
        run: |
          cmake ${{github.workspace}}/source/audio-switcher-exe `
            "-DCMAKE_INSTALL_PREFIX=${{runner.temp}}/com.morganscruggs.audioswitcherplus.sdPlugin"
      - name: Install static files
        working-directory: build/sdPlugin
        run: make install
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{runner.temp}}/artifacts
      - name: Display downloaded files
        run: ls -R
        working-directory: ${{runner.temp}}/artifacts
      - name: Combine MacOS artifacts
        working-directory: ${{runner.temp}}
        run: |
          lipo -create \
            artifacts/build-macos-arm64-RelWithDebInfo/sdaudioswitchplus \
            artifacts/build-macos-x86_64-RelWithDebInfo/sdaudioswitchplus \
            -output sdaudioswitchplus
          mkdir dsym
          cp -R \
            artifacts/build-macos-arm64-RelWithDebInfo/*.dSYM \
            dsym/sdaudioswitchplus.dSYM
          DSYM_FILE=Contents/Resources/DWARF/sdaudioswitchplus
          rm dsym/sdaudioswitchplus.dSYM/${DSYM_FILE}
          lipo -create \
            artifacts/build-macos*/*.dSYM/${DSYM_FILE} \
            -output dsym/sdaudioswitchplus.dSYM/${DSYM_FILE}
            (
              cd dsym
              zip -r sdaudioswitchplus.dSYM.zip sdaudioswitchplus.dSYM
            )
      - name: Upload MacOS debug symbols
        uses: actions/upload-artifact@v4
        with:
          name: package-macos-DebugSymbols
          path: ${{runner.temp}}/dsym/sdaudioswitchplus.dSYM.zip
      - name: Copy executables
        working-directory: ${{runner.temp}}
        run: |
          install -m755 \
            sdaudioswitchplus \
            com.morganscruggs.audioswitcherplus.sdPlugin/sdaudioswitchplus
          install -m755 \
            artifacts/build-windows-x86_64-RelWithDebInfo/sdaudioswitchplus.exe \
            com.morganscruggs.audioswitcherplus.sdPlugin/sdaudioswitchplus.exe
      - name: Checkout DistributionTool
        uses: actions/checkout@v4
        with:
          ref: distributiontool-v1.4
      - name: Build .streamDeckPlugin
        run: |
          ./DistributionTool -b \
            -i ${{runner.temp}}/com.morganscruggs.audioswitcherplus.sdPlugin \
            -o .
      - name: Upload .streamDeckPlugin
        uses: actions/upload-artifact@v4
        with:
          name: package-sdplugin
          path: com.morganscruggs.audioswitcherplus.streamDeckPlugin